[package]
name = "micromegas"
description = "Micromegas is a scalable observability solution."
readme = "README.md"
keywords.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
micromegas-analytics.workspace = true
micromegas-ingestion.workspace = true
micromegas-telemetry-sink.workspace = true
micromegas-telemetry.workspace = true
micromegas-tracing.workspace = true

object_store.workspace = true
