version: '3.0'

services:
  grafana:
    container_name: 'micromegas-micromegas-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.6.7}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/micromegas-micromegas-datasource
