[tool.poetry]
name = "micromegas"
version = "0.1.1"
description = "Python analytics client for https://github.com/madesroches/micromegas/"
authors = ["Marc-Antoine Desroches <madesroches@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cbor2 = "^5.6.3"
pyarrow = "^16.0.0"
requests = "^2.31.0"
pandas = "^2.2.2"
tabulate = "^0.9.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
