[tool.poetry]
name = "micromegas"
version = "0.6.0"
description = "Python analytics client for https://github.com/madesroches/micromegas/"
authors = ["Marc-Antoine Desroches <madesroches@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
cbor2 = "^5.6.3"
crc = "^7.0.0"
flatbuffers = "^24.12.23"
grpcio = "^1.69.0"
pandas = "^2.2.2"
protobuf = "^5.29.1"
pyarrow = "^18.1.0"
python = "^3.10"
requests = "^2.31.0"
tabulate = "^0.9.0"
tqdm = "^4.66.5"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
